### ISSUE TITLE
Values not correctly reported   Log file using your new debugging messages

### ISSUE THREAD

**Issue by SteveHoyt** [UniversalDevicesInc-PG3/udi-poly-FlumeWater#5]
Good Morning

I think I have a pretty good capture of when the reporting of values stops. See the log file attached and screen caps. . I had a circuit start this morning at 11:00 AM. If you check the last poll at 10:57 and the next one at 11:01 you will see the issue. For both polls GV1 and GV2  report as no change in value. I also saw no change in the ISY admin console. If you look at GV3 and GV4 in the same time period....GV3 went backward a bit while GV4 went forward. A bit later at 11:08 I restarted the node server and things came back. The admin console screen shot is after the restart of the node server.

I hope this helps. Let me know if I can do anything else or need me to test something. 

Also, I don't know if you saw my other post about me being able to programmatically request an update. It would be real easy to do what I want, if I could request the values to be updated in my program. The way I have it set up I have my "then" capture start values and my "else" ( which triggers when the circuit stops ) do the calculations. If I could force a query in the else life would be easy. 

Thanks
Steve
[FlumeWater_2-14-2022_110901_AM.txt](https://github.com/UniversalDevicesInc-PG3/udi-poly-FlumeWater/files/8063512/FlumeWater_2-14-2022_110901_AM.txt)
<img width="1158" alt="Screen Shot 2022-02-14 at 11 11 35 AM" src="https://user-images.githubusercontent.com/97555417/153934978-816b6b43-ba7e-4f51-8e20-a1b52ffcd1e0.png">
<img width="1158" alt="Screen Shot 2022-02-14 at 11 10 34 AM" src="https://user-images.githubusercontent.com/97555417/153935021-81b6b93d-0652-4db2-8882-f1678e7ebb23.png">
e

**Comment by jimboca** [comment]
There is a bug where it prints this line:
```
112022-02-14 10:56:59,847 Thread-5317 udi_interface      DEBUG    Flume2:update: Values={'current_interval': 0.0316301, 'today': 253.1356903, 'week_to_date': 253.1356903, 'month_to_date': 4857.2763065, 'last_60_min': 0.3479311, 'last_24_hrs': 284.8290505, 'last_30_days': 7014.5440168}
```
That's printed before the update, so it makes the log confusing...  I'll fix that but as well.

But, because of that, I can't see the reported values since the NS crashed when you ran a query on the Controller before the next update happened.  I'll fix that bug as well, but as I mentioned in your forum post, querying the controller won't query the sensor.

**Comment by jimboca** [comment]
Released 3.0.6 for both those issues, run your test again and then we can see if it's a flume issue or mine.

**Comment by SteveHoyt** [comment]
looks like 3.0.6 is having problem starting...gets key error

log info below

[FlumeWater_2-15-2022_40537_PM.txt](https://github.com/UniversalDevicesInc-PG3/udi-poly-FlumeWater/files/8075581/FlumeWater_2-15-2022_40537_PM.txt)
<img width="1131" alt="Screen Shot 2022-02-15 at 4 07 34 PM" src="https://user-images.githubusercontent.com/97555417/154171183-b3bfb6f3-ecc5-4114-a124-316db46a40df.png">
w

**Comment by jimboca** [comment]
Need to update your PG3 version, incompatible change in the PG3 Python interface was released:
```
sudo pkg update
sudo pkg upgrade
```

**Comment by SteveHoyt** [comment]
I had a suspicion that might be the issue. 

I was afraid to do it based on the problems I have seen. 

I’ll do it tomorrow and let you know how things go. 

I appreciate your help. 

I saw your message about query options. All of them don’t appear to be available in programs. I will send you a message when I have had time to formulate a coherent question. 

Sent via carrier pidgeon with big wings

**Comment by jimboca** [comment]
Version 3.0.7 now allows you to query the Sensor.
