### ISSUE TITLE
Track sprinkler usage

### ISSUE THREAD

**Issue by hart-2-hart** [UniversalDevicesInc-PG3/udi-poly-FlumeWater#7]
I water my lawn leading up to sunrise so no other water is used at that time.   I’d like to calculate water usage between sprinklers on and sprinklers off.  It’s not clear if current variables could do this but from watching them with sink turn on it’s not clear to me.  

If already possible, how? If not could it be added?

**Comment by hart-2-hart** [comment]
Latest log attached
[debug.log](https://github.com/UniversalDevicesInc-PG3/udi-poly-FlumeWater/files/8848781/debug.log)
.

**Comment by jimboca** [comment]
I think this is basically the same issue as #2, please re-open if I misunderstand.
